apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.21.0
    helm:
      releaseName: pihole
      values: |
        serviceDns:
          type: LoadBalancer
          loadBalancerIP: 192.168.1.246
          annotations:
            metallb.universe.tf/allow-shared-ip: "pihole-svc"

        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
          hosts:
            - host: pihole.local
              paths:
                - /

  destination:
    server: https://kubernetes.default.svc
    namespace: pihole

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
